# Generated by Django 5.0 on 2024-01-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
