# Generated by Django 4.2.5 on 2024-02-26 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="record",
            name="date_added",
        ),
    ]
