# Generated by Django 4.2.5 on 2024-02-26 20:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_remove_record_date_added"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="file",
            field=models.FileField(default=False, upload_to="uploads/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="record",
            name="title",
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
