# Generated by Django 4.2.5 on 2024-02-26 20:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_record_file_record_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="record",
            name="file",
        ),
        migrations.RemoveField(
            model_name="record",
            name="title",
        ),
        migrations.AddField(
            model_name="record",
            name="date_added",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
