# Generated by Django 4.2.5 on 2024-02-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_remove_record_file_remove_record_title_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="bad_IP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.CharField(max_length=50)),
                ("country", models.CharField(max_length=50)),
                ("continent", models.CharField(blank=True, max_length=50, null=True)),
                ("city", models.CharField(blank=True, max_length=50, null=True)),
                ("capital", models.CharField(blank=True, max_length=50, null=True)),
                ("datetime", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
