# Generated by Django 4.2.5 on 2024-02-26 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0005_bad_ip"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bad_ip",
            name="capital",
        ),
        migrations.RemoveField(
            model_name="bad_ip",
            name="city",
        ),
        migrations.RemoveField(
            model_name="bad_ip",
            name="continent",
        ),
        migrations.RemoveField(
            model_name="bad_ip",
            name="country",
        ),
        migrations.RemoveField(
            model_name="bad_ip",
            name="datetime",
        ),
    ]
