# Generated by Django 4.2.5 on 2024-01-27 20:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0006_delete_companies_record_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="file",
            field=models.FileField(
                default=django.utils.timezone.now, upload_to="files/", verbose_name=""
            ),
            preserve_default=False,
        ),
    ]
