# Generated by Django 4.2.5 on 2024-01-27 22:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0008_alter_record_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="title",
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
