# Generated by Django 4.2.5 on 2024-01-30 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0010_custumuser_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="custumuser",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="custumuser",
            name="user_permissions",
        ),
        migrations.DeleteModel(
            name="CODE",
        ),
        migrations.DeleteModel(
            name="CustumUser",
        ),
    ]
