# Generated by Django 4.2.5 on 2024-01-31 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0011_remove_custumuser_groups_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Monitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("continent", models.CharField(blank=True, max_length=50, null=True)),
                ("country", models.CharField(blank=True, max_length=50, null=True)),
                ("city", models.CharField(blank=True, max_length=50, null=True)),
                ("capital", models.CharField(blank=True, max_length=50, null=True)),
                ("datetime", models.DateField(blank=True, max_length=50, null=True)),
                ("ip", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
