# Generated by Django 4.2.5 on 2024-02-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0014_remove_cpu_load_datasaved_remove_cpu_load_unique_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cpu_load",
            name="dataSaved",
            field=models.BooleanField(default=False),
        ),
    ]
